{
 "title": "Monitoramento Projeto Korp",
 "panels": [
  {
   "title": "Total de Requisições",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "http_requests_total" }
   ]
  },
  {
   "title": "Disponibilidade",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Requisições por Segundo",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 10 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])" }
   ]
  }
 ]
}